# Generated by Django 5.2 on 2025-04-23 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_rename_title_ru_pokemon_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon_entities.pokemonentity'),
        ),
    ]
