# Generated by Django 5.2 on 2025-04-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_remove_pokemonentity_next_evolution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='next_evolution',
        ),
    ]
